Logian And Register
Hetic-web2-g1/Who_Got_Next pull request #6
Opened 2022-07-03 15:08 UTC by FlyLeBro

Pti test les reufs

2022-07-03 15:15 UTC, Erzenkell reviewed
aled

2022-07-03 15:16 UTC, Erzenkell submitted a review, later dismissed
bien de fou

2022-07-03 15:16 UTC, Erzenkell commented
c'était un test

2022-07-03 15:19 UTC, Erzenkell requested changes
wip

2022-07-03 15:19 UTC, FlyLeBro commented
> wip

je suggère

2022-07-08 23:22 UTC, Erzenkell approved these changes

2022-07-08 23:24 UTC, merged